### PR TITLE
RAINCATCH-647 Protractor Tests For fh-wfm-user UI module

### PR DESCRIPTION
**Pull request by vchepeli**

### CODE REVIEW

**Comment by secondsun** [comment]
As an additional thing I noticed, `browser.getLocationAbsUrl()` is deprecated and should be replaced with getCurrentUrl().

**Comment by vchepeli** [comment]
> As an additional thing I noticed, browser.getLocationAbsUrl() is deprecated and should be replaced with getCurrentUrl().

strange that I dont see any warnings from protractor

**Comment by secondsun** [comment]
As I linked in #3  http://www.protractortest.org/#/api?view=ProtractorBrowser.prototype.getLocationAbsUrl

It is in their documentaiton.

**Comment by vchepeli** [comment]
> As I linked in #3 http://www.protractortest.org/#/api?view=ProtractorBrowser.prototype.getLocationAbsUrl
> 
> It is in their documentaiton.

I use protractor@4 still and this command should be there but in near future it should be migrated to protractor@6 and this change is needed

**Comment by secondsun** [comment]
@vchepeli Any reason we can't use protractor 5?

**Pull request merged**
